#!/bin/bash

ynh_nodejs_try_bash_extension() {
  if [ -x src/configure ]; then
    src/configure && make -C src || {
      ynh_print_info --message="Optional bash extension failed to build, but things will still work normally."
    }
  fi
}

nodenv_install_dir="/opt/nodenv"
nodejs_version_path="$nodenv_install_dir/versions"
# NODENV_ROOT is the directory of nodenv, it needs to be loaded as a environment variable.
export NODENV_ROOT="$nodenv_install_dir"

# Load the version of Node.js for an app, and set variables.
#
# ynh_use_nodejs has to be used in any app scripts before using Node.js for the first time.
# This helper will provide alias and variables to use in your scripts.
#
# To use npm or node, use the alias `ynh_npm` and `ynh_node`
# Those alias will use the correct version installed for the app
# For example: use `ynh_npm install` instead of `npm install`
#
# With `sudo` or `ynh_exec_as`, use instead the fallback variables `$ynh_npm` and `$ynh_node`
# And propagate $PATH to sudo with $ynh_node_load_path
# Exemple: `ynh_exec_as $app $ynh_node_load_path $ynh_npm install`
#
# $PATH contains the path of the requested version of Node.js.
# However, $PATH is duplicated into $nodejs_path to outlast any manipulation of $PATH
# You can use the variable `$ynh_node_load_path` to quickly load your Node.js version
#  in $PATH for an usage into a separate script.
# Exemple: $ynh_node_load_path $final_path/script_that_use_npm.sh`
#
#
# Finally, to start a Node.js service with the correct version, 2 solutions
#  Either the app is dependent of Node.js or npm, but does not called it directly.
#  In such situation, you need to load PATH
#    `Environment="__YNH_NODE_LOAD_PATH__"`
#    `ExecStart=__FINALPATH__/my_app`
#     You will replace __YNH_NODE_LOAD_PATH__ with $ynh_node_load_path
#
#  Or Node.js start the app directly, then you don't need to load the PATH variable
#    `ExecStart=__YNH_NODE__ my_app run`
#     You will replace __YNH_NODE__ with $ynh_node
#
#
# one other variable is also available
#   - $nodejs_path: The absolute path to Node.js binaries for the chosen version.
#
# usage: ynh_use_nodejs
#
# Requires YunoHost version 3.2.2 or higher.
ynh_use_nodejs () {
    nodejs_version=$(ynh_app_setting_get --app=$app --key=nodejs_version)

    # Get the absolute path of this version of Node.js
    nodejs_path="$nodejs_version_path/$YNH_APP_INSTANCE_NAME/bin"

    # Allow alias to be used into bash script
    shopt -s expand_aliases

    # Create an alias for the specific version of Node.js and a variable as fallback
    ynh_node="$nodejs_path/node"
    alias ynh_node="$ynh_node"
    # And npm
    ynh_npm="$nodejs_path/npm"
    alias ynh_npm="$ynh_npm"

    # Load the path of this version of Node.js in $PATH
    if [[ :$PATH: != *":$nodejs_path"* ]]; then
        PATH="$nodejs_path:$PATH"
    fi
    # Create an alias to easily load the PATH
    ynh_node_load_PATH="PATH=$PATH"
    # Same var but in lower case to be compatible with ynh_replace_vars...
    ynh_nodejs_load_path="PATH=$PATH"

    # Sets the local application-specific Node.js version
    pushd $final_path
        $nodenv_install_dir/bin/nodenv local $nodejs_version
    popd
}

# Install a specific version of Node.js
#
# ynh_install_nodejs will install the version of Node.js provided as argument by using nodenv.
#
# This helper creates a /etc/profile.d/nodenv.sh that configures PATH environment for nodenv
# for every LOGIN user, hence your user must have a defined shell (as opposed to /usr/sbin/nologin)
#
# Don't forget to execute Node.js-dependent command in a login environment
# (e.g. sudo --login option)
# When not possible (e.g. in systemd service definition), please use direct path
# to nodenv shims (e.g. $NODENV_ROOT/shims/bundle)
#
# usage: ynh_install_nodejs --nodejs_version=nodejs_version
# | arg: -v, --nodejs_version= - Version of Node.js to install.
#
# Requires YunoHost version 3.2.2 or higher.
ynh_install_nodejs () {
    # Declare an array to define the options of this helper.
    local legacy_args=v
    local -A args_array=( [v]=nodejs_version= )
    local nodejs_version
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"

    # Load nodenv path in PATH
    local CLEAR_PATH="$nodenv_install_dir/bin:$PATH"

    # Remove /usr/local/bin in PATH in case of Node.js prior installation
    PATH=$(echo $CLEAR_PATH | sed 's@/usr/local/bin:@@')

    # Move an existing Node.js binary, to avoid to block nodenv
    test -x /usr/bin/node && mv /usr/bin/node /usr/bin/node_n
    test -x /usr/bin/npm && mv /usr/bin/npm /usr/bin/npm_n

    # Install or update nodenv
    nodenv="$(command -v nodenv $nodenv_install_dir/bin/nodenv | head -1)"
    if [ -n "$nodenv" ]; then
        ynh_print_info --message="nodenv already seems installed in \`$nodenv'."
        pushd "${nodenv%/*/*}"
            if git remote -v 2>/dev/null | grep "https://github.com/nodenv/nodenv.git"; then
                echo "Trying to update with git..."
                git pull -q --tags origin master
                cd ..
                ynh_nodejs_try_bash_extension
            fi
        popd
    else
        ynh_print_info --message="Installing nodenv with git..."
        mkdir -p $nodenv_install_dir
        pushd $nodenv_install_dir
            git init -q
            git remote add -f -t master origin https://github.com/nodenv/nodenv.git > /dev/null 2>&1
            git checkout -q -b master origin/master
            ynh_nodejs_try_bash_extension
            nodenv=$nodenv_install_dir/bin/nodenv
        popd
    fi

    node_build="$(command -v "$nodenv_install_dir"/plugins/*/bin/nodenv-install nodenv-install | head -1)"
    if [ -n "$node_build" ]; then
        ynh_print_info --message="\`nodenv install' command already available in \`$node_build'."
        pushd "${node_build%/*/*}"
            if git remote -v 2>/dev/null | grep "https://github.com/nodenv/node-build.git"; then
                ynh_print_info --message="Trying to update nodenv with git..."
                git pull -q origin master
            fi
        popd
    else
        ynh_print_info --message="Installing node-build with git..."
        mkdir -p "${nodenv_install_dir}/plugins"
        git clone -q https://github.com/nodenv/node-build.git "${nodenv_install_dir}/plugins/node-build"
    fi

    nodenv_alias="$(command -v "$nodenv_install_dir"/plugins/*/bin/nodenv-alias nodenv-alias | head -1)"
    if [ -n "$nodenv_alias" ]; then
        ynh_print_info --message="\`nodenv alias' command already available in \`$nodenv_alias'."
        pushd "${nodenv_alias%/*/*}"
            if git remote -v 2>/dev/null | grep "https://github.com/nodenv/nodenv-aliases.git"; then
                ynh_print_info --message="Trying to update nodenv-aliases with git..."
                git pull -q origin master
            fi
        popd
    else
        ynh_print_info --message="Installing nodenv-aliases with git..."
        mkdir -p "${nodenv_install_dir}/plugins"
        git clone -q https://github.com/nodenv/nodenv-aliases.git "${nodenv_install_dir}/plugins/nodenv-aliase"
    fi

    nodenv_latest="$(command -v "$nodenv_install_dir"/plugins/*/bin/nodenv-latest nodenv-latest | head -1)"
    if [ -n "$nodenv_latest" ]; then
        ynh_print_info --message="\`nodenv latest' command already available in \`$nodenv_latest'."
        pushd "${nodenv_latest%/*/*}"
            if git remote -v 2>/dev/null | grep "https://github.com/momo-lab/xxenv-latest.git"; then
                ynh_print_info --message="Trying to update xxenv-latest with git..."
                git pull -q origin master
            fi
        popd
    else
        ynh_print_info --message="Installing xxenv-latest with git..."
        mkdir -p "${nodenv_install_dir}/plugins"
        git clone -q https://github.com/momo-lab/xxenv-latest.git "${nodenv_install_dir}/plugins/xxenv-latest"
    fi

    # Enable caching
    mkdir -p "${nodenv_install_dir}/cache"

    # Create shims directory if needed
    mkdir -p "${nodenv_install_dir}/shims"

    # Restore /usr/local/bin in PATH
    PATH=$CLEAR_PATH

    # And replace the old Node.js binary
    test -x /usr/bin/node_n && mv /usr/bin/node_n /usr/bin/node
    test -x /usr/bin/npm_n && mv /usr/bin/npm_n /usr/bin/npm

    # Install the requested version of Node.js
    local final_nodejs_version=$(nodenv latest --print $nodejs_version)
    ynh_print_info --message="Installation of Node.js-$nodejs_version"
    nodenv install --skip-existing $final_nodejs_version > /dev/null 2>&1

    # Store nodejs_version into the config of this app
    ynh_app_setting_set --app=$YNH_APP_INSTANCE_NAME --key=nodejs_version --value=$final_nodejs_version

    # Remove app virtualenv
    if  `nodenv alias --list | grep --quiet "$YNH_APP_INSTANCE_NAME " 1>/dev/null 2>&1`
    then
        nodenv alias $YNH_APP_INSTANCE_NAME --remove
    fi

    # Create app virtualenv
    nodenv alias $YNH_APP_INSTANCE_NAME $nodejs_version

    # Cleanup Node.js versions
    ynh_cleanup_nodejs

    # Set environment for Node.js users
    echo  "#nodenv
export NODENV_ROOT=$nodenv_install_dir
export PATH=\"$nodenv_install_dir/bin:$PATH\"
eval \"\$(nodenv init -)\"
#nodenv" > /etc/profile.d/nodenv.sh

    # Load the environment
    eval "$(nodenv init -)"
}

# Remove the version of Node.js used by the app.
#
# This helper will also cleanup Node.js versions
#
# usage: ynh_remove_nodejs
ynh_remove_nodejs () {
    local nodejs_version=$(ynh_app_setting_get --app=$YNH_APP_INSTANCE_NAME --key=nodejs_version)

    # Load nodenv path in PATH
    local CLEAR_PATH="$nodenv_install_dir/bin:$PATH"

    # Remove /usr/local/bin in PATH in case of Node.js prior installation
    PATH=$(echo $CLEAR_PATH | sed 's@/usr/local/bin:@@')

    nodenv alias $YNH_APP_INSTANCE_NAME --remove

    # Remove the line for this app
    ynh_app_setting_delete --app=$YNH_APP_INSTANCE_NAME --key=nodejs_version

    # Cleanup Node.js versions
    ynh_cleanup_nodejs
}

# Remove no more needed versions of Node.js used by the app.
#
# This helper will check what Node.js version are no more required,
# and uninstall them
# If no app uses Node.js, nodenv will be also removed.
#
# usage: ynh_cleanup_nodejs
ynh_cleanup_nodejs () {

    # List required Node.js versions
    local installed_apps=$(yunohost app list --output-as json --quiet | jq -r .apps[].id)
    local required_nodejs_versions=""
    for installed_app in $installed_apps
    do
        local installed_app_nodejs_version=$(ynh_app_setting_get --app=$installed_app --key="nodejs_version")
        if [[ $installed_app_nodejs_version ]]
        then
            required_nodejs_versions="${installed_app_nodejs_version}\n${required_nodejs_versions}"
        fi
    done
    
    # Remove no more needed Node.js versions
    local installed_nodejs_versions=$(nodenv versions --bare --skip-aliases | grep -Ev '/')
    for installed_nodejs_version in $installed_nodejs_versions
    do
        if ! `echo ${required_nodejs_versions} | grep "${installed_nodejs_version}" 1>/dev/null 2>&1`
        then
            ynh_print_info --message="Removing of Node.js-$installed_nodejs_version"
            $nodenv_install_dir/bin/nodenv uninstall --force $installed_nodejs_version
        fi
    done

    # If none Node.js version is required
    if [[ ! $required_nodejs_versions ]]
    then
        # Remove nodenv environment configuration
        ynh_print_info --message="Removing of nodenv-"$nodenv_version
        ynh_secure_remove --file="$nodenv_install_dir"
        ynh_secure_remove --file="/etc/profile.d/nodenv.sh"
        
        # Remove previous n Version Management
        n_install_dir="/opt/node_n"
        ynh_secure_remove --file="$n_install_dir"
        ynh_secure_remove --file="/usr/local/n"
        sed --in-place "/$n_install_dir/d" /root/.bashrc
        ynh_secure_remove --file="/etc/cron.daily/node_update"
    fi
}
