#!/bin/bash

PSQL_ROOT_PWD_FILE=/etc/yunohost/psql
PSQL_VERSION=13

# Open a connection as a user
#
# usage: ynh_psql_connect_as --user=user --password=password [--database=database]
# | arg: -u, --user=        - the user name to connect as
# | arg: -p, --password=    - the user password
# | arg: -d, --database=    - the database to connect to
#
# examples:
#    ynh_psql_connect_as 'user' 'pass' <<< "UPDATE ...;"
#    ynh_psql_connect_as 'user' 'pass' < /path/to/file.sql
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_connect_as() {
    # Declare an array to define the options of this helper.
    local legacy_args=upd
    local -A args_array=([u]=user= [p]=password= [d]=database=)
    local user
    local password
    local database
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"
    database="${database:-}"

    sudo --login --user=postgres PGUSER="$user" PGPASSWORD="$password" psql "$database"
}

# Execute a command as root user
#
# usage: ynh_psql_execute_as_root --sql=sql [--database=database]
# | arg: -s, --sql=         - the SQL command to execute
# | arg: -d, --database=    - the database to connect to
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_execute_as_root() {
    # Declare an array to define the options of this helper.
    local legacy_args=sd
    local -A args_array=([s]=sql= [d]=database=)
    local sql
    local database
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"
    database="${database:-}"

    if [ -n "$database" ]; then
        database="--database=$database"
    fi

    ynh_psql_connect_as --user="postgres" --password="$(cat $PSQL_ROOT_PWD_FILE)" \
        $database <<<"$sql"
}

# Execute a command from a file as root user
#
# usage: ynh_psql_execute_file_as_root --file=file [--database=database]
# | arg: -f, --file=        - the file containing SQL commands
# | arg: -d, --database=    - the database to connect to
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_execute_file_as_root() {
    # Declare an array to define the options of this helper.
    local legacy_args=fd
    local -A args_array=([f]=file= [d]=database=)
    local file
    local database
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"
    database="${database:-}"

    if [ -n "$database" ]; then
        database="--database=$database"
    fi

    ynh_psql_connect_as --user="postgres" --password="$(cat $PSQL_ROOT_PWD_FILE)" \
        $database <"$file"
}

# Create a database and grant optionnaly privilegies to a user
#
# [internal]
#
# usage: ynh_psql_create_db db [user]
# | arg: db - the database name to create
# | arg: user - the user to grant privilegies
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_create_db() {
    local db=$1
    local user=${2:-}

    local sql="CREATE DATABASE ${db};"

    # grant all privilegies to user
    if [ -n "$user" ]; then
        sql+="ALTER DATABASE ${db} OWNER TO ${user};"
        sql+="GRANT ALL PRIVILEGES ON DATABASE ${db} TO ${user} WITH GRANT OPTION;"
    fi

    ynh_psql_execute_as_root --sql="$sql"
}

# Drop a database
#
# [internal]
#
# If you intend to drop the database *and* the associated user,
# consider using ynh_psql_remove_db instead.
#
# usage: ynh_psql_drop_db db
# | arg: db - the database name to drop
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_drop_db() {
    local db=$1
    # First, force disconnection of all clients connected to the database
    # https://stackoverflow.com/questions/17449420/postgresql-unable-to-drop-database-because-of-some-auto-connections-to-db
    ynh_psql_execute_as_root --sql="REVOKE CONNECT ON DATABASE $db FROM public;" --database="$db"
    ynh_psql_execute_as_root --sql="SELECT pg_terminate_backend (pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$db' AND pid <> pg_backend_pid();" --database="$db"
    sudo --login --user=postgres dropdb $db
}

# Dump a database
#
# usage: ynh_psql_dump_db --database=database
# | arg: -d, --database=    - the database name to dump
# | ret: the psqldump output
#
# example: ynh_psql_dump_db 'roundcube' > ./dump.sql
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_dump_db() {
    # Declare an array to define the options of this helper.
    local legacy_args=d
    local -A args_array=([d]=database=)
    local database
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"

    sudo --login --user=postgres pg_dump "$database"
}

# Dump all existing PostgreSQL databases associated with a given user
#
# usage: ynh_psql_dump_all_user_dbs --db_user=db_user [--app=app]
# | arg: -u, --db_user=    - the PostgreSQL role/user of which to remove all owned databases
# | arg: -a, --app=     - the application id to tag the dump with
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_dump_all_user_dbs() {
    # Declare an array to define the options of this helper.
    local legacy_args=ua
    local -A args_array=([u]=db_user= [a]=app=)
    local db_user
    local app
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"
    app="${app:-}"
	
	local dbs_to_dump=$(ynh_psql_list_user_dbs $db_user)
	if [ -n "$dbs_to_dump" ]; then	   # Check that the list of database(s) is not empty 
		
		local db_name
		for db_name in $dbs_to_dump   # Iterate through the list of database(s) to dump. Note: this would fail in case databases names would contain space character or characters such as "*". IFS parsing method would then be required. 
		do
			if ynh_psql_database_exists --database=$db_name; then # Check if the database exists
				ynh_psql_dump_db $db_name > "$app-$db_name-dump.sql" # Dump the database to a filename format of app-db_name-dump.sql, or of db_name-dump.sql if app parameter was not supplied  
				ynh_print_info --message="Dumped database $db_name associated to role $db_user"
			else
				ynh_print_warn --message="Database $db_name not found"
			fi
		done
	else 
		ynh_print_warn --message="No associated database to role $db_user was found"
	fi
}

# Restore all dumped PostgreSQL databases for the given app
#
# usage: ynh_psql_restore_all_app_dbs_dumps --db_user=db_user [--db_user_pwd=db_user_pwd]
# | arg: -u, --db_user=    		- the PostgreSQL role/user which will own the restored databases. If not existing, it will be created.
# | arg: -p, --db_user_pwd= 	- the password associated to the PostgreSQL role/user which will own the databases. If not existing, it will be generated and saved to the app's config file.
#	
# SQL dump files to restore must be named according to this format "app_id-db_name-dump.sql" (e.g. "noalyss-account_repository-dump.sql") and be located in the app folder 
# The filename format requirement is so in order to match the files dumped using ynh_psql_dump_all_user_dbs --user=user --app=app (with both parameters specified).
# 
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_restore_all_app_dbs_dumps(){
    # Declare an array to define the options of this helper.
    local legacy_args=up
    local -A args_array=([u]=db_user= [p]=db_user_pwd=)
    local db_user
    local db_user_pwd
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"	
	
	if [ -z "$app" ]; then
		ynh_die --message="No global app_ID variable defined in the script"
	fi

	ynh_psql_test_if_first_run  # Make sure PSQL is installed
	
	local filename
	for filename in *-dump.sql	# Loop among all files ending with "-dump.sql" in the current folder  
	do	
		local db_name
		db_name="${filename#${app}-}"							# Remove "$app-" prefix from filename string to parse db_name. Will do nothing if there is no match.
		db_name="${db_name%-dump.sql}"							# Remove "-dump.sql" suffix from filename string to parse db_name. Will do nothing if there is no match.
		db_name=$(ynh_sanitize_dbid --db_name="$db_name")
		
		if [[ "${filename#${app}-}" = "$filename" || -z "$db_name" ]] ; then  	# Check whether app_ID is included in filename OR $db_name is empty
			ynh_print_warn --message="File ignored: $filename. Filename not matching expected format (appID-db_name-dump.sql)"
			continue												
		else														
		    db_user_pwd="${db_user_pwd:-}"
			if [ -z "$db_user_pwd" ]; then 
				db_user_pwd=$(ynh_app_setting_get --app=$app --key=psqlpwd) 				# Try to retrieve db_user_pwd from the app's settings. It may prove empty during the first loop, but will get populated before the second loop by ynh_psql_setup_db() below.   
			fi
			
			ynh_psql_setup_db --db_user=$db_user --db_name=$db_name --db_pwd=$db_user_pwd	# Check that the db_user exists or create it generating a random password and then create an empty database named $db_name.  
			ynh_psql_execute_file_as_root --file="./${filename}" --database=$db_name		# Restore the dabatase from the corresponding dump file
			
			ynh_print_info --message="Restored database $db_name, owned by PostgreSQL user $db_user"
		fi
	done	
}

# Create a user
#
# [internal]
#
# usage: ynh_psql_create_user user pwd
# | arg: user - the user name to create
# | arg: pwd - the password to identify user by
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_create_user() {
    local user=$1
    local pwd=$2
    ynh_psql_execute_as_root --sql="CREATE USER $user WITH ENCRYPTED PASSWORD '$pwd'"
}

# Check if a psql user exists
#
# usage: ynh_psql_user_exists --user=user
# | arg: -u, --user=    - the user for which to check existence
# | exit: Return 1 if the user doesn't exist, 0 otherwise
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_user_exists() {
    # Declare an array to define the options of this helper.
    local legacy_args=u
    local -A args_array=([u]=user=)
    local user
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"

    if ! sudo --login --user=postgres PGUSER="postgres" PGPASSWORD="$(cat $PSQL_ROOT_PWD_FILE)" psql -tAc "SELECT rolname FROM pg_roles WHERE rolname='$user';" | grep --quiet "$user"; then
        return 1
    else
        return 0
    fi
}

# Check if a psql database exists
#
# usage: ynh_psql_database_exists --database=database
# | arg: -d, --database=    - the database for which to check existence
# | exit: Return 1 if the database doesn't exist, 0 otherwise
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_database_exists() {
    # Declare an array to define the options of this helper.
    local legacy_args=d
    local -A args_array=([d]=database=)
    local database
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"

    # if psql is not there, we cannot check the db
    # though it could exists.
    if ! command -v psql
    then
      ynh_print_err -m "PostgreSQL is not installed, impossible to check for db existence."
      return 1
    elif ! sudo --login --user=postgres PGUSER="postgres" PGPASSWORD="$(cat $PSQL_ROOT_PWD_FILE)" psql -tAc "SELECT datname FROM pg_database WHERE datname='$database';" | grep --quiet "$database"; then
        return 1
    else
        return 0
    fi
}

# Drop a user
#
# [internal]
#
# usage: ynh_psql_drop_user user
# | arg: user - the user name to drop
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_drop_user() {
    ynh_psql_execute_as_root --sql="DROP USER ${1};"
}

# Create a database, an user and its password. Then store the password in the app's config
#
# usage: ynh_psql_setup_db --db_user=user --db_name=name [--db_pwd=pwd]
# | arg: -u, --db_user=     - Owner of the database
# | arg: -n, --db_name=     - Name of the database
# | arg: -p, --db_pwd=      - Password of the database. If not provided, a password will be generated
#
# After executing this helper, the password of the created database will be available in $db_pwd
# It will also be stored as "psqlpwd" into the app settings.
#
# Requires YunoHost version 2.7.13 or higher.
ynh_psql_setup_db() {
    # Declare an array to define the options of this helper.
    local legacy_args=unp
    local -A args_array=([u]=db_user= [n]=db_name= [p]=db_pwd=)
    local db_user
    local db_name
    db_pwd=""
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"

    if ! ynh_psql_user_exists --user=$db_user; then
        local new_db_pwd=$(ynh_string_random) # Generate a random password
        # If $db_pwd is not provided, use new_db_pwd instead for db_pwd
        db_pwd="${db_pwd:-$new_db_pwd}"

        ynh_psql_create_user "$db_user" "$db_pwd"
    elif [ -z $db_pwd ]; then
        ynh_die --message="The user $db_user exists, please provide his password"
    fi

    ynh_psql_create_db "$db_name" "$db_user"                     # Create the database
    ynh_app_setting_set --app=$app --key=psqlpwd --value=$db_pwd # Store the password in the app's config
}

# Remove a database if it exists, and the associated user
#
# usage: ynh_psql_remove_db --db_user=user --db_name=name
# | arg: -u, --db_user=     - Owner of the database
# | arg: -n, --db_name=     - Name of the database
#
# Requires YunoHost version 2.7.13 or higher.
ynh_psql_remove_db() {
    # Declare an array to define the options of this helper.
    local legacy_args=un
    local -A args_array=([u]=db_user= [n]=db_name=)
    local db_user
    local db_name
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"

    if ynh_psql_database_exists --database=$db_name; then # Check if the database exists
        ynh_psql_drop_db $db_name                         # Remove the database
    else
        ynh_print_warn --message="Database $db_name not found"
    fi

    # Remove psql user if it exists
    if ynh_psql_user_exists --user=$db_user; then
        ynh_psql_drop_user $db_user
    else
        ynh_print_warn --message="User $db_user not found"
    fi
}

# Remove all existing PostgreSQL databases associated with a given user
#
# usage: ynh_psql_remove_all_user_dbs --db_user=db_user
# | arg: -u, --db_user=    - the PostgreSQL role/user of which to remove all owned databases
#
# This can be useful to prepare the removal of a given user.
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_remove_all_user_dbs() {
    # Declare an array to define the options of this helper.
    local legacy_args=u
    local -A args_array=([u]=db_user=)
    local db_user
    # Manage arguments with getopts
    ynh_handle_getopts_args "$@"
	
	local dbs_to_drop=$(ynh_psql_list_user_dbs $db_user) 
	if [ -n "$dbs_to_drop" ]; then	   # Check that the list of database(s) is not empty 
		
		local db_name
		for db_name in $dbs_to_drop   # Iterate through the list of database(s) to remove. Note: this would fail in case databases names would contain space character or characters such as "*". IFS parsing method would then be required. 
		do
			if ynh_psql_database_exists --database=$db_name; then # Check if the database exists
				ynh_psql_drop_db $db_name                         # Remove the database
				ynh_print_info --message="Removed database $db_name associated to role $db_user"
			else
				ynh_print_warn --message="Database $db_name not found"
			fi
		done
	else 
		ynh_print_warn --message="No associated database to role $db_user was found"
	fi
}

# Create a master password and set up global settings
#
# [internal]
#
# usage: ynh_psql_test_if_first_run
#
# It also make sure that postgresql is installed and running
# Please always call this script in install and restore scripts
#
# Requires YunoHost version 2.7.13 or higher.
ynh_psql_test_if_first_run() {

    # Make sure postgresql is indeed installed
    dpkg --list | grep -q "ii  postgresql-$PSQL_VERSION" || ynh_die --message="postgresql-$PSQL_VERSION is not installed !?"

    yunohost tools regen-conf postgresql
}

# List all existing PostgreSQL databases associated with a given user
#
# [internal]
#
# usage: ynh_psql_list_user_dbs db_user
# | arg: db_user  - the PostgreSQL role/user of which to list all owned databases
#
# Requires YunoHost version 3.5.0 or higher.
ynh_psql_list_user_dbs() {
    local db_user=$1
	
    if ynh_psql_user_exists --user=$db_user; then # Check that the db_user exists
        local sql="COPY (SELECT datname FROM pg_database JOIN pg_authid ON pg_database.datdba = pg_authid.oid WHERE rolname = '${db_user}') TO STDOUT"
        local dbs_list=$(ynh_psql_execute_as_root --sql="$sql") # Fetch database(s) associated to role $db_user as a string using space as delimiter (ex: "db1 db2 db3 db4")
        echo "$dbs_list"
    else
        ynh_print_err --message="User \'$db_user\' does not exist"
        echo ""
    fi
}
