dnsmasq:
  test_conf: dnsmasq --test
dovecot:
  log: [/var/log/mail.log,/var/log/mail.err]
  needs_exposed_ports: [993]
  category: email
fail2ban:
  log: /var/log/fail2ban.log
  category: security
  test_conf: fail2ban-server --test
metronome:
  log: [/var/log/metronome/metronome.log,/var/log/metronome/metronome.err]
  needs_exposed_ports: [5222, 5269]
  category: xmpp
  ignore_if_package_is_not_installed: metronome
mysql:
  log: [/var/log/mysql.log,/var/log/mysql.err,/var/log/mysql/error.log]
  actual_systemd_service: mariadb
  category: database
  ignore_if_package_is_not_installed: mariadb-server
nginx:
  log: /var/log/nginx
  test_conf: nginx -t
  needs_exposed_ports: [80, 443]
  category: web
# Yunohost will dynamically add installed php-fpm services (7.3, 7.4, 8.0, ...) in services.py
#php7.4-fpm:
#  log: /var/log/php7.4-fpm.log
#  test_conf: php-fpm7.4 --test
#  category: web
postfix:
  log: [/var/log/mail.log,/var/log/mail.err]
  actual_systemd_service: postfix@-
  needs_exposed_ports: [25, 587]
  category: email
postgresql:
  actual_systemd_service: 'postgresql@13-main'
  category: database
  ignore_if_package_is_not_installed: postgresql-13
redis-server:
  log: /var/log/redis/redis-server.log
  category: database
rspamd:
  log: /var/log/rspamd/rspamd.log
  category: email
slapd:
  category: database
  test_conf: slapd -Tt
ssh:
  log: /var/log/auth.log
  test_conf: sshd -t
  needs_exposed_ports: [22]
  category: admin
yunohost-api:
  log: /var/log/yunohost/yunohost-api.log
  category: admin
yunohost-firewall:
  need_lock: true
  test_status: iptables -S | grep "^-A INPUT" | grep " --dport" | grep -q ACCEPT
  category: security
yunomdns:
  category: mdns
glances: null
nsswitch: null
ssl: null
yunohost: null
bind9: null
tahoe-lafs: null
memcached: null
udisks2: null
udisk-glue: null
amavis: null
postgrey: null
spamassassin: null
rmilter: null
php5-fpm: null
php7.0-fpm: null
php7.3-fpm: null
nslcd: null
avahi-daemon: null
