#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -eu

do_init_regen() {
    do_pre_regen ""
    systemctl restart sssd
}

do_pre_regen() {
    pending_dir=$1
    config_dir=/usr/share/yunohost/conf

    install -D -m 644 "$config_dir/nsswitch/nsswitch.conf" "$pending_dir/etc/nsswitch.conf"
    install -D -m 640 "$config_dir/sssd/sssd.conf" "$pending_dir/etc/sssd/sssd.conf"
}

do_post_regen() {
    regen_conf_files=$1

    chmod 644 "/etc/nsswitch.conf"
    chmod 640 "/etc/sssd/sssd.conf"

    if [[ -n "$regen_conf_files" ]]; then
        sss_cache -E
        systemctl restart sssd
    fi
}

"do_$1_regen" "$(echo "${*:2}" | xargs)"
