#!/bin/bash

set -e

if ! dpkg --list | grep -q 'ii *rspamd '
then
    echo 'rspamd is not installed, skipping'
    exit 0
fi

do_pre_regen() {
    pending_dir=$1

    cd /usr/share/yunohost/conf/rspamd

    install -D -m 644 metrics.local.conf \
        "${pending_dir}/etc/rspamd/local.d/metrics.conf"
    install -D -m 644 rspamd.sieve \
        "${pending_dir}/etc/dovecot/global_script/rspamd.sieve"
	install -D -m 644 redis.conf \
		"${pending_dir}/etc/rspamd/local.d/redis.conf"

    # Old conf file to be deleted
    touch "${pending_dir}/etc/rspamd/local.d/dkim_signing.conf"
}

do_post_regen() {

    [ ! -e /var/log/rspamd ] || chown -R _rspamd:_rspamd /var/log/rspamd

    regen_conf_files=$1
    [ -z "$regen_conf_files" ] && exit 0

    # compile sieve script
    [[ "$regen_conf_files" =~ rspamd\.sieve ]] && {
        sievec /etc/dovecot/global_script/rspamd.sieve
        chown -R vmail:mail /etc/dovecot/global_script
        systemctl restart dovecot
    }

    # Restart rspamd due to the upgrade
    # https://rspamd.com/announce/2016/08/01/rspamd-1.3.1.html
    systemctl -q restart rspamd.service
}

do_$1_regen ${@:2}
