#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -Eeuo pipefail

do_init_regen() {
    do_pre_regen ""
    systemctl restart unscd
}

do_pre_regen() {
    pending_dir=$1

    cd /usr/share/yunohost/conf/nsswitch

    install -D -m 644 nsswitch.conf "$pending_dir/etc/nsswitch.conf"
}

do_post_regen() {
    regen_conf_files=$1

    if [[ -n "$regen_conf_files" ]]; then
        systemctl restart unscd
    fi
}

"do_$1_regen" "$(echo "${*:2}" | xargs)"
