#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
# shellcheck source=../../helpers/helpers
source /usr/share/yunohost/helpers

do_pre_regen() {
    pending_dir=$1

    reaction_dir="${pending_dir}/etc/reaction"
    mkdir -p "${reaction_dir}/"
    mkdir -p "${pending_dir}/etc/systemd/system/reaction.service.d/"

    cp /usr/share/yunohost/conf/reaction/*.jsonnet "$pending_dir"
    cp /usr/share/yunohost/conf/reaction/systemd-override-bind-nftables.conf "${pending_dir}/etc/systemd/system/reaction.service.d/"
}

do_post_regen() {
    regen_conf_files=$1

    chown -R root:root /etc/reaction/
    chmod 755 /etc/reaction/
    chmod 644 /etc/reaction/*

    if [[ -n "$regen_conf_files" ]]; then
        systemctl restart reaction
    fi
}

"do_$1_regen" "$(echo "${*:2}" | xargs)"
