#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -Eeuo pipefail

# Source YNH helpers
YNH_HELPERS_VERSION=2.1
# shellcheck source=../../helpers/helpers
source /usr/share/yunohost/helpers

YNH_CORE_BACKUP_DIR="${YNH_BACKUP_DIR%/}/conf/ynh"

ynh_restore /etc/yunohost/current_host
ynh_restore /etc/yunohost/firewall.yml
# Note we need to handle the old and the new backup path
# ${YNH_CORE_BACKUP_DIR}/etc/yunohost/permissions.yml is the new one whereas ${YNH_CORE_BACKUP_DIR}/permissions.yml is the old one
{ [ ! -e "${YNH_CORE_BACKUP_DIR}/etc/yunohost/permissions.yml" ] && [ ! -e "${YNH_CORE_BACKUP_DIR}/permissions.yml" ]; } || ynh_restore /etc/yunohost/permissions.yml
{ [ ! -d "${YNH_CORE_BACKUP_DIR}/etc/yunohost/portal" ] && [ ! -d "${YNH_CORE_BACKUP_DIR}/portal" ]; } || ynh_restore '/etc/yunohost/portal'
{ [ ! -d "${YNH_CORE_BACKUP_DIR}/etc/yunohost/domains" ] && [ ! -d "${YNH_CORE_BACKUP_DIR}/domains" ]; } || ynh_restore '/etc/yunohost/domains'
{ [ ! -e "${YNH_CORE_BACKUP_DIR}/etc/yunohost/settings.yml" ] && [ ! -e "${YNH_CORE_BACKUP_DIR}/settings.yml" ]; } || ynh_restore '/etc/yunohost/settings.yml'
{ [ ! -d "${YNH_CORE_BACKUP_DIR}/etc/yunohost/dyndns" ] && [ ! -d "${YNH_CORE_BACKUP_DIR}/dyndns" ]; } || ynh_restore '/etc/yunohost/dyndns'
{ [ ! -d "${YNH_CORE_BACKUP_DIR}/etc/dkim" ] && [ ! -d "${YNH_CORE_BACKUP_DIR}/dkim" ]; } || ynh_restore '/etc/dkim'
