#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Source YNH helpers
YNH_HELPERS_VERSION=2.1
# shellcheck source=../../helpers/helpers
source /usr/share/yunohost/helpers

ynh_restore '/etc/yunohost/current_host'
ynh_restore '/etc/yunohost/firewall.yml'
# NB : these may not exists on some older backups
# ./etc/yunohost/permissions.yml is the new one whereas ./permissions.yml is the old one
{ [ ! -e "./etc/yunohost/permissions.yml" ] && [ ! -e "./permissions.yml" ]; } || ynh_restore /etc/yunohost/permissions.yml
{ [ ! -d "./etc/yunohost/portal" ] && [ ! -d "./portal" ]; } || ynh_restore '/etc/yunohost/portal'
{ [ ! -d "./etc/yunohost/domains" ] && [ ! -d "./domains" ]; } || ynh_restore '/etc/yunohost/domains'
{ [ ! -e "./etc/yunohost/settings.yml" ] && [ ! -e "./settings.yml" ]; } || ynh_restore '/etc/yunohost/settings.yml'
{ [ ! -d "./etc/yunohost/dyndns" ] && [ ! -d "./dyndns" ]; } || ynh_restore '/etc/yunohost/dyndns'
{ [ ! -d "./etc/dkim" ] && [ ! -d "./dkim" ]; } || ynh_restore '/etc/dkim'
