#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -Eeuo pipefail

# Source YNH helpers
YNH_HELPERS_VERSION=2.1
# shellcheck source=../../helpers/helpers
source /usr/share/yunohost/helpers

YNH_CORE_BACKUP_DIR="${YNH_BACKUP_DIR%/}/conf/manually_modified_files"

for file in $(cat "$YNH_CORE_BACKUP_DIR/manually_modified_files_list"); do
    ynh_restore "$file" || true
done

[ ! -e "${YNH_CORE_BACKUP_DIR}/etc/ssowat/conf.json.persistent" ] || ynh_restore '/etc/ssowat/conf.json.persistent'
