---
title: App resources
template: docs
taxonomy:
    category: docs
routes:
  default: '/packaging_apps_resources'
custom_edit_link: 'https://github.com/YunoHost/yunohost/blob/dev/src/utils/resources.py'
---

Doc auto-generated by [this script](https://github.com/YunoHost/yunohost/blob/{{current_commit}}/doc/generate_resource_doc.py) on {{date}} (YunoHost version {{version}})
{% for section_id, docstring in resources.items() %}
## {{section_id}}

{{docstring}}
{% if not loop.last %}
---
{% endif %}
{%- endfor %}
