[sssd]
domains = LDAP

[nss]
filter_groups = root
filter_users = root

[pam]

[sudo]

[ssh]

[domain/LDAP]
id_provider = ldap
auth_provider = ldap
chpass_provider = ldap
sudo_provider = ldap

ldap_uri = ldaps://localhost:636
ldap_search_base = dc=yunohost,dc=org

ldap_tls_reqcert = allow
ldap_tls_cacert = /etc/yunohost/certs/yunohost.org/crt.pem
ldap_tls_key = /etc/yunohost/certs/yunohost.org/key.pem

cache_credentials = True
