#!/bin/bash
set -e 

force=$1

function safe_copy () {
    if [ $force ]; then
        sudo yunohost service safecopy \
          -s ssl $1 $2 --force
    else
        sudo yunohost service safecopy \
          -s ssl $1 $2
    fi
}

cd /usr/share/yunohost/templates/ssl
ssl_dir=/usr/share/yunohost/yunohost-config/ssl/yunoCA

sudo mkdir -p /etc/yunohost/certs/yunohost.org
sudo mkdir -p $ssl_dir/{ca,certs,crl,newcerts}

if [ ! -f $ssl_dir/serial ]; then
    echo "01" | sudo tee $ssl_dir/serial
fi

if [ ! -f /etc/yunohost/current_host ]; then
    echo "yunohost.org" | sudo tee /etc/yunohost/current_host
fi

if [ ! -f /etc/yunohost/certs/yunohost.org/crt.pem ]; then
    sudo openssl req -new -config $ssl_dir/openssl.cnf \
      -days 730 -out $ssl_dir/certs/yunohost_csr.pem \
      -keyout $ssl_dir/certs/yunohost_key.pem -nodes -batch 
    sudo openssl ca -config $ssl_dir/openssl.cnf \
      -days 730 -in $ssl_dir/certs/yunohost_csr.pem \
      -out $ssl_dir/certs/yunohost_crt.pem -batch
    sudo cp $ssl_dir/ca/cacert.pem \
      /etc/yunohost/certs/yunohost.org/ca.pem
    sudo cp $ssl_dir/certs/yunohost_key.pem \
      /etc/yunohost/certs/yunohost.org/key.pem
    sudo cp $ssl_dir/yunoCA/newcerts/01.pem \
      /etc/yunohost/certs/yunohost.org/crt.pem
    sudo ln -s /etc/yunohost/certs/yunohost.org/crt.pem \
      /etc/ssl/certs/yunohost_crt.pem
    sudo ln -s /etc/yunohost/certs/yunohost.org/key.pem \
      /etc/ssl/private/yunohost_key.pem
    sudo ln -s /etc/yunohost/certs/yunohost.org/ca.pem \
      /etc/ssl/certs/ca-yunohost_crt.pem
    sudo update-ca-certificates
fi
