#!/bin/bash

set -e

do_pre_regen() {
  pending_dir=$1

  cd /usr/share/yunohost/templates/ssh

  # Don't overwrite configuration if from_script
  if [[ ! -f /etc/yunohost/from_script ]]; then
      # do not listen to IPv6 if unavailable
      [[ -f /proc/net/if_inet6 ]] \
        || sed -i "s/ListenAddress ::/#ListenAddress ::/g" sshd_config

      # Support legacy setting (this setting might be disabled by a user during a migration)
      if [[ "$(yunohost settings get 'service.ssh.allow_deprecated_dsa_hostkey')" == "True" ]]; then
          sed -i '/HostKey \/etc\/ssh\/ssh_host_rsa_key/a HostKey /etc/ssh/ssh_host_dsa_key' sshd_config
      fi

      install -D -m 644 sshd_config "${pending_dir}/etc/ssh/sshd_config"
  fi
}

do_post_regen() {
  regen_conf_files=$1

  if [[ ! -f /etc/yunohost/from_script ]]; then
    [[ -z "$regen_conf_files" ]] \
      || sudo service ssh restart
  fi
}

FORCE=${2:-0}
DRY_RUN=${3:-0}

case "$1" in
  pre)
    do_pre_regen $4
    ;;
  post)
    do_post_regen $4
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
