#!/bin/bash

set -e

. /usr/share/yunohost/helpers

do_pre_regen() {
  pending_dir=$1

  cd /usr/share/yunohost/templates/postfix

  postfix_dir="${pending_dir}/etc/postfix"
  mkdir -p "$postfix_dir"

  default_dir="${pending_dir}/etc/default/"
  mkdir -p "$default_dir"

  # install plain conf files
  cp plain/* "$postfix_dir"

  # prepare main.cf conf file
  main_domain=$(cat /etc/yunohost/current_host)

  # Support different strategy for security configurations
  export compatibility="$(yunohost settings get 'security.postfix.compatibility')"

  export smtp_relayhost="$(yunohost settings get 'smtp.relayhost')"
  export smtp_relayhost_user="$(yunohost settings get 'smtp.relayhost_user')"
  export smtp_relayhost_pass="$(yunohost settings get 'smtp.relayhost_pass')"

  if [[ -n "$smtp_relayhost" ]]; then
    echo -e "${smtp_relayhost} ${smtp_relayhost_user}:${smtp_relayhost_pass}" > /etc/postfix/sasl/relayhost_passwd
    chmod 600 /etc/postfix/sasl/relayhost_passwd
    postmap /etc/postfix/sasl/relayhost_passwd
  fi

  export main_domain
  export domain_list="$YNH_DOMAINS"
  ynh_render_template "main.cf" "${postfix_dir}/main.cf"

  cat postsrsd \
    | sed "s/{{ main_domain }}/${main_domain}/g" \
    | sed "s/{{ domain_list }}/${YNH_DOMAINS}/g" \
    > "${default_dir}/postsrsd"

  # adapt it for IPv4-only hosts
  ipv6="$(yunohost settings get 'smtp.allow_ipv6')"
  if [ "$ipv6" == "False" ] || [ ! -f /proc/net/if_inet6 ]; then
    sed -i \
      's/ \[::ffff:127.0.0.0\]\/104 \[::1\]\/128//g' \
      "${postfix_dir}/main.cf"
    sed -i \
      's/inet_interfaces = all/&\ninet_protocols = ipv4/' \
      "${postfix_dir}/main.cf"
  fi
}

do_post_regen() {
  regen_conf_files=$1

  [[ -z "$regen_conf_files" ]] \
    || { service postfix restart && service postsrsd restart; }

}

FORCE=${2:-0}
DRY_RUN=${3:-0}

case "$1" in
  pre)
    do_pre_regen $4
    ;;
  post)
    do_post_regen $4
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
