#!/bin/bash
set -e 

# Add new email services
sudo yunohost service add rspamd -l /var/log/mail.log \
  || echo "Rspamd is already listed in services"

sudo yunohost service add rmilter -l /var/log/mail.log \
  || echo "Rspamd is already listed in services"

sudo yunohost service add memcached \
  || echo "Memcached is already listed in services"

# Remove previous email services
sudo yunohost service remove spamassassin \
  || echo "Spamassassin is already removed" \
  && sudo systemctl disable spamassassin || true

sudo yunohost service remove amavis \
  || echo "Amavis is already removed" \
  && sudo systemctl disable amavis || true

sudo yunohost service remove postgrey \
  || echo "Postgrey is already removed" \
  && sudo systemctl disable postgrey || true
