#!/bin/bash
set -e 

force=$1

function safe_copy () {
    if [[ "$force" == "True" ]]; then
        sudo yunohost service safecopy \
          -s postgrey \
          $1 $2 \
          --force
    else
        sudo yunohost service safecopy \
          -s postgrey \
          $1 $2
    fi
}

cd /usr/share/yunohost/templates/postgrey

if [[ "$(safe_copy postgrey.default /etc/default/postgrey)" == "True" ]]; then
    sudo service nslcd restart
fi
