#!/bin/bash
set -e 

force=$1

function safe_copy () {
    if [[ "$force" == "True" ]]; then
        sudo yunohost service safecopy \
          -s rspamd $1 $2 --force
    else
        sudo yunohost service safecopy \
          -s rspamd $1 $2
    fi
}

cd /usr/share/yunohost/templates/rspamd

# Copy Rspamd configuration
safe_copy metrics.conf /etc/rspamd/metrics.conf

# Install Rspamd sieve script
safe_copy rspamd.sieve /etc/dovecot/global_script/rspamd.sieve
sudo sievec /etc/dovecot/global_script/rspamd.sieve
sudo chmod 660 /etc/dovecot/global_script/rspamd.svbin
sudo chown -R vmail:mail /etc/dovecot/global_script

# Ensure that the socket is listening and stop the service.
sudo systemctl stop rspamd.service 2>&1 || true
sudo systemctl start rspamd.socket

sudo systemctl restart dovecot
