#!/bin/bash

do_pre_regen() {
    :
}

do_post_regen() {
    # Enforce these damn permissions because for some reason in some weird cases
    # they are spontaneously replaced by root:root -_-
    chown -R redis:adm /var/log/redis
}

do_$1_regen ${@:2}
