#!/bin/bash

do_pre_regen() {
}

do_post_regen() {
  # Enforce these damn permissions because for some reason in some weird cases
  # they are spontaneously replaced by root:root -_-
  chown -R redis:adm /var/log/redis
}

FORCE=${2:-0}
DRY_RUN=${3:-0}

case "$1" in
  pre)
    do_pre_regen $4
    ;;
  post)
    do_post_regen $4
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
