#!/bin/bash

set -e

do_pre_regen() {
  pending_dir=$1

  cd /usr/share/yunohost/templates/avahi-daemon

  install -D avahi-daemon.conf "${pending_dir}/etc/avahi/avahi-daemon.conf"
}

do_post_regen() {
  sudo service avahi-daemon restart
}

FORCE=$2

case "$1" in
  pre)
    do_pre_regen $3
    ;;
  post)
    do_post_regen
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
