#!/bin/bash
set -e 

force=$1

function safe_copy () {
    if [[ "$force" == "True" ]]; then
        sudo yunohost service safecopy \
          -s glances $1 $2 --force
    else
        sudo yunohost service safecopy \
          -s glances $1 $2
    fi
}

cd /usr/share/yunohost/templates/glances

if [[ "$(safe_copy glances.default /etc/default/glances)" == "True" ]]; then
    sudo service glances restart
fi
