#!/bin/bash
set -e 

force=$1

function safe_copy () {
    if [[ "$force" == "True" ]]; then
        sudo yunohost service safecopy \
          -s nsswitch $1 $2 --force
    else
        sudo yunohost service safecopy \
          -s nsswitch $1 $2
    fi
}

cd /usr/share/yunohost/templates/nsswitch

if [[ "$(safe_copy nsswitch.conf /etc/nsswitch.conf)" == "True" ]]; then
    sudo service nscd restart
fi
