#!/bin/bash

set -e

do_init_regen() {
  do_pre_regen ""
  systemctl restart unscd
}

do_pre_regen() {
  pending_dir=$1

  cd /usr/share/yunohost/templates/nsswitch

  install -D -m 644 nsswitch.conf "${pending_dir}/etc/nsswitch.conf"
}

do_post_regen() {
  regen_conf_files=$1

  [[ -z "$regen_conf_files" ]] \
    || systemctl restart unscd
}

FORCE=${2:-0}
DRY_RUN=${3:-0}

case "$1" in
  pre)
    do_pre_regen $4
    ;;
  post)
    do_post_regen $4
    ;;
  init)
    do_init_regen
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
