#!/bin/bash
set -e 

force=$1

function safe_copy () {
    if [[ "$force" == "True" ]]; then
        sudo yunohost service safecopy \
          -s udisks-glue $1 $2 --force
    else
        sudo yunohost service safecopy \
          -s udisks-glue $1 $2
    fi
}

cd /usr/share/yunohost/templates/udisks-glue

if [[ "$(safe_copy udisks-glue.conf /etc/udisks-glue.conf)" == "True" ]]; then
    sudo service udisks-glue restart
fi
