#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# See https://manpages.debian.org/testing/dpkg-dev/deb-postrm.5.en.html
# to understand when / how this script is called...

set -e

if [ "$1" = "purge" ]; then
    update-rc.d yunohost-firewall remove >/dev/null
    rm -f /etc/yunohost/installed
fi

if [ "$1" = "remove" ]; then
    rm -f /etc/yunohost/installed
fi

# Reset dpkg vendor to debian
# see https://wiki.debian.org/Derivatives/Guidelines#Vendor
rm -f /etc/dpkg/origins/default
ln -s /etc/dpkg/origins/debian /etc/dpkg/origins/default

#DEBHELPER#

exit 0
