#!/bin/bash

set -e

if [ -x /etc/init.d/yunohost-api ] && ! [ -d /run/systemd/system ]; then
    invoke-rc.d yunohost-api stop || exit $?
    invoke-rc.d yunohost-firewall stop || true
fi

#DEBHELPER#

exit 0
