#!/bin/bash

# Create a dedicated nginx config
#
# usage: ynh_add_nginx_config
#
# This will use a template in `../conf/nginx.conf`
# See the documentation of `ynh_add_config` for a description of the template
# format and how placeholders are replaced with actual variables.
#
# Additionally, ynh_add_nginx_config will replace:
# - `#sub_path_only`      by empty string if `path` is not `'/'`
# - `#root_path_only`     by empty string if `path`  *is*  `'/'`
#
# This allows to enable/disable specific behaviors dependenging on the install
# location
#
# Requires YunoHost version 4.1.0 or higher.
ynh_add_nginx_config() {

    local finalnginxconf="/etc/nginx/conf.d/$domain.d/$app.conf"

    ynh_add_config --template="nginx.conf" --destination="$finalnginxconf"

    if [ "${path:-}" != "/" ]; then
        ynh_replace --match="^#sub_path_only" --replace="" --file="$finalnginxconf"
    else
        ynh_replace --match="^#root_path_only" --replace="" --file="$finalnginxconf"
    fi

    ynh_store_file_checksum --file="$finalnginxconf"

    ynh_systemd_action --service_name=nginx --action=reload
}

# Remove the dedicated nginx config
#
# usage: ynh_remove_nginx_config
#
# Requires YunoHost version 2.7.2 or higher.
ynh_remove_nginx_config() {
    ynh_safe_rm --target="/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_systemd_action --service_name=nginx --action=reload
}


# Regen the nginx config in a change url context
#
# usage: ynh_change_url_nginx_config
#
# Requires YunoHost version 11.1.9 or higher.
ynh_change_url_nginx_config() {

    # Make a backup of the original NGINX config file if manually modified
    # (nb: this is possibly different from the same instruction called by
    # ynh_add_config inside ynh_add_nginx_config because the path may have 
    # changed if we're changing the domain too...)
    local old_nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf
    ynh_backup_if_checksum_is_different --file="$old_nginx_conf_path"
    ynh_delete_file_checksum --file="$old_nginx_conf_path"
    ynh_safe_rm --target="$old_nginx_conf_path"

    # Regen the nginx conf
    ynh_add_nginx_config
}
