#!/usr/bin/env bash

ynh_config_add_reaction() {
    # ============ Argument parsing =============
    local -A args_array=([l]=logpath= [r]=failregex=)
    local logpath
    local failregex
    ynh_handle_getopts_args "$@"
    # ===========================================

    # If failregex is provided, Build a config file on-the-fly using $logpath and $failregex
    if [[ -n "${failregex:-}" ]]; then
        test -n "$logpath" || ynh_die "ynh_config_add_reaction expects a logfile path as first argument and received nothing."

        echo "
local ban = import '_ban.jsonnet';
{
  streams: {
    __APP__: {
      cmd: ['tail', '-Fn0', '__LOGPATH__'],
      filters: {
        failedlogin: {
          regex: [
            @'__FAILREGEX__',
          ],
          retry: 5,
          retryperiod: '6h',
          actions: ban(time='12h', service='http,https'),
        },
      },
    },
  },
}
" > "$YNH_APP_BASEDIR/conf/reaction.jsonnet"

    fi

    ynh_config_add --template="reaction.jsonnet" --destination="/etc/reaction/app-$app.jsonnet"

    if ! reaction test-config -c /etc/reaction; then
      ynh_print_error "reaction failed to load the filter for $app"
      rm "/etc/reaction/app-$app.jsonnet"
      exit 1
    fi

    # Create the folder and logfile if they don't exist
    local logdir=$(dirname "$logpath")
    if [ ! -d "$logdir" ]; then
        mkdir -p "$logdir"
        # Make sure log folder's permissions are correct
        chown "$app:$app" "$logdir"
        chmod u=rwX,g=rX,o= "$logdir"
    fi

    if [ ! -f "$logpath" ]; then
        touch "$logpath"
        # Make sure log file's permissions are correct
        chown "$app:$app" "$logpath"
        chmod u=rwX,g=rX,o= "$logpath"
    fi

    ynh_systemctl --service=reaction --action=restart --wait_until="(Started|Reloaded) reaction.service" --log_path=systemd

    local reaction_error="$(journalctl --no-hostname --unit=reaction | tail --lines=50 | grep -E "(ERROR[WARN).*$app.*")"
    if [[ -n "$reaction_error" ]]; then
        ynh_print_warn "reaction failed to load the filter for $app"
        ynh_print_warn "${reaction_error#*WARNING}"
    fi
}
