#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
YNH_HELPERS_VERSION=2.1
# shellcheck source=../../helpers/helpers
source /usr/share/yunohost/helpers

# Backup user home
# NB : we use 'find' to avoid using * / globbing which has possible pitfalls such as
# nullglobs, not matching entries starting with dots, etc...
# The printf %f allows to obtain only the file name, without the basedir in front
for f in $(find /home/ -mindepth 1 -prune -type d -printf '%f\n'); do
    # Filter-out stuff like yunohost.multimedia, yunohost.app
    # as well as home dirs flagged to not be backed up using the .nobackup file flag
    if [[ ! "$f" =~ ^yunohost|lost\+found ]] && [[ ! -e "/home/$f/.nobackup" ]]; then
        ynh_backup "/home/$f"
    fi
done
