#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

# Backup destination
backup_dir="${1}/data/multimedia"

if [ -e "/home/yunohost.multimedia/.nobackup" ]; then
    exit 0
fi

# Backup multimedia directory
ynh_backup --src_path="/home/yunohost.multimedia/Music" --dest_path="${backup_dir}/Music" --is_big --not_mandatory
ynh_backup --src_path="/home/yunohost.multimedia/Picture" --dest_path="${backup_dir}/Picture" --is_big --not_mandatory
ynh_backup --src_path="/home/yunohost.multimedia/Video" --dest_path="${backup_dir}/Video" --is_big --not_mandatory
ynh_backup --src_path="/home/yunohost.multimedia/eBook" --dest_path="${backup_dir}/eBook" --is_big --not_mandatory
