#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Exit hook on subcommand error or unset variable
set -Eeuo pipefail

# Source YNH helpers
YNH_HELPERS_VERSION=2.1
# shellcheck source=../../helpers/helpers
source /usr/share/yunohost/helpers

# Backup destination
YNH_CORE_BACKUP_DIR="${YNH_BACKUP_DIR%/}/conf/ynh"

# Backup the configuration
ynh_backup "/etc/yunohost/firewall.yml"
ynh_backup "/etc/yunohost/permissions.yml"
ynh_backup "/etc/yunohost/current_host"
[ ! -d "/etc/yunohost/portal" ] || ynh_backup "/etc/yunohost/portal"
[ ! -d "/etc/yunohost/domains" ] || ynh_backup "/etc/yunohost/domains"
[ ! -e "/etc/yunohost/settings.yml" ] || ynh_backup "/etc/yunohost/settings.yml"
[ ! -d "/etc/yunohost/dyndns" ] || ynh_backup "/etc/yunohost/dyndns"
[ ! -d "/etc/dkim" ] || ynh_backup "/etc/dkim"
