import os
import base64
import hashlib
import tempfile
import subprocess
import datetime
from logging import getLogger
from typing import Any, Literal, Generator
from pydantic import BaseModel

from moulinette import m18n
from moulinette.utils.filesystem import (
    read_file,
    write_to_file,
    chmod,
    chown,
    rm,
    mkdir,
)
from yunohost.app import (
    _hydrate_app_template,
    _get_app_settings,
    _set_app_settings,
    APPS_SETTING_PATH,
)
from yunohost.service import service_reload_or_restart
from yunohost.utils.error import YunohostError

logger = getLogger("yunohost.utils.resources")

DIR_TO_BACKUP_CONF_MANUALLY_MODIFIED = "/var/cache/yunohost/appconfbackup"

JSExpression = str
IFClause = Literal[True] | JSExpression


def sym_to_octal(sym: str) -> int:

    assert len(sym) == 9

    owner_perm, group_perm, other_perm = sym[:3], sym[3:6], sym[6:]

    owner_perm_octal = (
        (4 if "r" in owner_perm else 0)
        + (2 if "w" in owner_perm else 0)
        + (1 if "x" in owner_perm else 0)
    )

    group_perm_octal = (
        (4 if "r" in group_perm else 0)
        + (2 if "w" in group_perm else 0)
        + (1 if "x" in group_perm else 0)
    )

    other_perm_octal = (
        (4 if "r" in other_perm else 0)
        + (2 if "w" in other_perm else 0)
        + (1 if "x" in other_perm else 0)
    )

    return (
        0o100 * owner_perm_octal + 0o010 * group_perm_octal + 0o001 * other_perm_octal
    )


class BaseConfiguration(BaseModel):

    # if_clause: IFClause = True
    template: str
    path: str

    # FIXME: These should be settable via the manifest ... except for type = "app" for owner/group/perms ?
    id: str
    app: str
    type: str
    content: str | None = None
    env: dict[str, Any]
    owner: str = "root"
    group: str = "root"
    perms: str = "rw-r--r--"

    @property
    def name(self):
        return self.type if self.id != "main" else f"{self.type}.{self.id}"

    def exists(self):
        return os.path.exists(self.path)

    def render(self, template_content) -> None:
        self.content = _hydrate_app_template(
            template_content, self.env, raise_exception_if_missing_var=True
        )

    def checksum(self) -> str:
        assert self.content
        return hashlib.md5(self.content.encode()).hexdigest()

    def write(self, content):
        write_to_file(self.path, content)
        chown(self.path, self.owner, self.group)
        chmod(self.path, sym_to_octal(self.perms))

    ###############################################################
    # The 'original' conf refers to the original configuration    #
    # as generated by YunoHost / the app templates, *before* the  #
    # admins may have possibly manually edited it, compared to    #
    # the 'current' on-disk conf.                                 #
    ###############################################################

    def original_checksum(self):
        settings = _get_app_settings(self.app)
        checksum = (
            settings.get("_configurations", {})
            .get(f"{self.type}.{self.id}", {})
            .get("md5")
        )
        if not checksum:
            # Legacy way of storing checksums...
            legacy_checksum_setting_name = (
                f"checksum_{self.path.replace('/', '_').replace(' ', '_')}"
            )
            checksum = settings.get(legacy_checksum_setting_name)

        return checksum

    def original_content(self) -> str | None:

        original_checksum_ = self.original_checksum()
        if not original_checksum_:
            return None

        original_conf_file = os.path.join(
            APPS_SETTING_PATH, self.app, ".original_confs", original_checksum_
        )
        if os.path.exists(original_conf_file):
            try:
                # FIXME : should we revalidate the checksum here?
                return base64.b64decode(read_file(original_conf_file).encode()).decode()
            except Exception as e:
                logger.warning(f"Failed to read original conf for {self.name}? {e}")

        return None

    def save_new_original_content_and_checksum(self) -> None:

        assert self.content is not None

        new_checksum = self.checksum()
        original_conf_dir = os.path.join(APPS_SETTING_PATH, self.app, ".original_confs")
        original_conf_file = os.path.join(original_conf_dir, new_checksum)
        os.makedirs(original_conf_dir, exist_ok=True)
        chmod(original_conf_dir, 0o770)
        try:
            write_to_file(
                original_conf_file, base64.b64encode(self.content.encode()).decode()
            )
        except Exception as e:
            raise YunohostError(f"Failed to write original conf for {self.name}? {e}")

        app_settings = _get_app_settings(self.app)
        if "_configurations" not in app_settings:
            app_settings["_configurations"] = {}
        app_settings["_configurations"][f"{self.type}.{self.id}"] = {
            "path": self.path,
            "md5": new_checksum,
        }
        _set_app_settings(self.app, app_settings)

    ##########################################################
    # The 'current' conf refers to the current, on-disk file #
    ##########################################################

    @property
    def current_path(self) -> str | None:
        settings = _get_app_settings(self.app)
        path = (
            settings.get("_configurations", {})
            .get(f"{self.type}.{self.id}", {})
            .get("path")
        )
        if path:
            return path if os.path.exists(path) else None
        else:
            # Mostly to handle migration from packaging v2 ... is it enough though
            return self.path if os.path.exists(self.path) else None

    def current_content(self) -> str:
        current_path = self.current_path
        return read_file(current_path) if current_path else ""

    def current_checksum(self) -> str | None:
        current_content = self.current_content()
        return (
            hashlib.md5(current_content.encode()).hexdigest()
            if current_content
            else None
        )

    def backup_current_conf(self):

        current_path = self.current_path
        if not current_path:
            logger.warning(
                f"Configuration {self.path} doesn't exists and therefore won't be backedup?"
            )
            return

        timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_file = f"{DIR_TO_BACKUP_CONF_MANUALLY_MODIFIED}/{self.app}/{self.path}.backup.{timestamp}"
        mkdir(os.path.dirname(backup_file), mode=0o700, parents=True, uid="root")
        write_to_file(backup_file, self.current_content())

        # FIXME : i18n
        logger.warning(
            f"Configuration {current_path} was manually modified since the installation or last upgrade. It has been backedup in {backup_file}"
        )

    ##########################################################

    def was_manually_modified(self) -> bool:
        return self.current_checksum() != self.original_checksum()

    def attempt_merge(self) -> tuple[bool, str]:
        new_c = self.content
        original_c = self.original_content()
        current_c = self.current_content()
        assert new_c is not None
        assert original_c is not None
        assert current_c is not None

        with tempfile.NamedTemporaryFile(
            mode="w"
        ) as new_f, tempfile.NamedTemporaryFile(
            mode="w"
        ) as original_f, tempfile.NamedTemporaryFile(
            mode="w"
        ) as current_f:
            new_f.write(new_c)
            new_f.flush()
            original_f.write(original_c)
            original_f.flush()
            current_f.write(current_c)
            current_f.flush()
            p = subprocess.run(
                [
                    "git",
                    "merge-file",
                    "-p",
                    "--zdiff3",
                    "-L",
                    "current_config",
                    "-L",
                    "original_config",
                    "-L",
                    "new_config",
                    current_f.name,
                    original_f.name,
                    new_f.name,
                ],
                capture_output=True,
            )
            merged_content = p.stdout.decode()

        return (p.returncode == 0, merged_content)

    def original_vs_current_diff(self) -> str:
        original_c = self.original_content()
        current_c = self.current_content()
        assert original_c is not None
        assert current_c is not None

        with tempfile.NamedTemporaryFile(
            mode="w"
        ) as original_f, tempfile.NamedTemporaryFile(mode="w") as current_f:
            original_f.write(original_c)
            original_f.flush()
            current_f.write(current_c)
            current_f.flush()
            p = subprocess.run(
                [
                    "git",
                    "--no-pager",
                    "diff",
                    "--color",
                    "--no-index",
                    original_f.name,
                    current_f.name,
                ],
                capture_output=True,
            )

            out = p.stdout.decode().strip().split("\n")
            # [5:] is to Remove the diff header
            out = out[5:]
            # Remove the 'No newline at end of file' stuff...
            out = [l for l in out if not l.startswith("\\")]

            return "\n".join(out)

    def apply(
        self,
        dry_run: bool = False,
        force: bool = False,
    ):

        self.render(read_file(self.template))

        current_path = self.current_path
        if current_path is None:
            logger.debug(f"Adding {self.name} configuration ({self.path})")

        elif (
            not force
            and self.original_checksum() == self.checksum()
            and (not current_path or current_path == self.path)
        ):
            logger.debug(f"{self.name} does not need to be updated")
            return
        else:
            logger.debug(f"Updating {self.name} configuration ({self.path})")

        content_to_write = self.content
        conf_was_manually_modified = (
            self.was_manually_modified() if current_path is not None else False
        )

        if current_path and conf_was_manually_modified:
            merge_success, merged_content = self.attempt_merge()

            if merge_success:
                # FIXME: i18n
                logger.info(
                    f"Configuration {current_path} appears to have been manually modified. YunoHost was able to automatically merged your changes with the new configuration."
                )
                content_to_write = merged_content
            else:
                original_vs_current_diff = self.original_vs_current_diff()
                # FIXME: i18n
                logger.warning(
                    f"Configuration {current_path} appears to have been manually modified. YunoHost was unable to automatically merge your changes with the new configuration. It will therefore instead backup the current configuration and apply the new configuration. You may want to manually re-apply your changes:\n{'#'*16}\n{original_vs_current_diff}\n{'#'*16}"
                )

        if not dry_run:
            if current_path and conf_was_manually_modified:
                self.backup_current_conf()

            if current_path and current_path != self.path:
                logger.debug(
                    f"Removing old conf {current_path} since new conf is now at {self.path}"
                )
                rm(current_path)
            self.save_new_original_content_and_checksum()
            self.write(content_to_write)

    def remove(self, dry_run: bool = False):
        if not self.exists():
            logger.warning(f"Configuration {self.name}: {self.path} is already absent")
            return

        if dry_run:
            logger.debug(f"Would remove {self.name} configuration ({self.path})")
            return

        if not dry_run:
            logger.debug(f"Removing {self.name} configuration ({self.path})")
            rm(self.path)


class AppConfigurationsManager:

    def __init__(self, app: str, current: dict, wanted: dict, workdir=None) -> None:
        self.app = app
        self.current = current
        self.wanted = wanted
        self.workdir = workdir

        if "configurations" not in self.current:
            self.current["configurations"] = {}
        if "env" not in self.current:
            self.current["env"] = {}
        if "configurations" not in self.wanted:
            self.wanted["configurations"] = {}
        if "env" not in self.wanted:
            self.wanted["env"] = {}

    def compute_todos(
        self,
    ) -> Generator[
        tuple[
            Literal["add", "update", "remove"],
            str,
            str,
            BaseConfiguration | None,
            BaseConfiguration | None,
        ],
        None,
        None,
    ]:

        current_confs = {
            k: ConfigurationsClassesByType[k](v, self.app, self.current["env"])
            for k, v in self.current["configurations"].items()
        }
        wanted_confs = {
            k: ConfigurationsClassesByType[k](
                v, self.app, self.wanted["env"], self.workdir
            )
            for k, v in self.wanted["configurations"].items()
        }

        for type_, confs in current_confs.items():
            current_confs_for_this_type = confs.confs
            wanted_confs_for_this_type = (
                wanted_confs[type_].confs if wanted_confs.get(type_) else {}
            )
            for id_, conf in current_confs_for_this_type.items():
                if id_ not in wanted_confs_for_this_type:
                    yield ("remove", type_, id_, conf, None)

        for type_, confs in wanted_confs.items():
            current_confs_for_this_type = (
                current_confs[type_].confs if current_confs.get(type_) else {}
            )
            wanted_confs_for_this_type = confs.confs
            for id_, conf in wanted_confs_for_this_type.items():
                if id_ in current_confs_for_this_type:
                    yield ("update", type_, id_, current_confs_for_this_type[id_], conf)
                else:
                    yield ("add", type_, id_, None, conf)

    def apply(
        self,
        rollback_and_raise_exception_if_failure,
        operation_logger=None,
        dry_run=False,
    ) -> None:
        todos = list(self.compute_todos())
        completed = []
        rollback = False
        exception = None

        for todo, type_, id_, old, new in todos:
            name = type_ if id_ == "main" else f"{type_}.{id_}"
            try:
                if todo == "remove":
                    assert old
                    logger.info(f"Removing {name} configuration...")
                    old.remove(dry_run=dry_run)
                elif todo == "add":
                    assert new
                    logger.info(f"Adding {name} configuration...")
                    new.apply(dry_run=dry_run)
                elif todo == "update":
                    assert old and new
                    logger.info(f"Updating {name} configuration...")
                    new.apply(dry_run=dry_run)
                if not dry_run:
                    ConfigurationsClassesByType[type_].reload()
            except (KeyboardInterrupt, Exception) as e:
                exception = e
                if isinstance(e, KeyboardInterrupt):
                    logger.error(m18n.n("operation_interrupted"))
                else:
                    logger.error(f"Failed to {todo} {name} configuration : {e}")
                if rollback_and_raise_exception_if_failure:
                    rollback = True
                    completed.append((todo, type_, id_, old, new))
                    break
                else:
                    pass
            else:
                completed.append((todo, type_, id_, old, new))

        if rollback:
            for todo, type_, id_, old, new in completed:
                name = type_ if id_ == "main" else f"{type_}.{id_}"
                try:
                    # (NB. here we want to undo the todo)
                    if todo == "remove":
                        assert old
                        # FIXME : i18n, better info strings
                        logger.info(f"Rollingback {name} configuration...")
                        old.apply(dry_run=dry_run)
                    elif todo == "add":
                        assert new
                        logger.info(f"Removing {name} configuration...")
                        new.remove(dry_run=dry_run)
                    elif todo == "update":
                        assert old and new
                        logger.info(f"Rollingback {name} configuration...")
                        old.apply(dry_run=dry_run)
                    if not dry_run:
                        ConfigurationsClassesByType[type_].reload()
                except (KeyboardInterrupt, Exception) as e:
                    if isinstance(e, KeyboardInterrupt):
                        logger.error(m18n.n("operation_interrupted"))
                    else:
                        logger.error(f"Failed to rollback {name} : {e}")

        if exception:
            if rollback_and_raise_exception_if_failure:
                logger.error(
                    m18n.n("app_regenconf_failed", app=self.app, error=exception)
                )
                if operation_logger:
                    failure_message_with_debug_instructions = operation_logger.error(
                        str(exception)
                    )
                    raise YunohostError(
                        failure_message_with_debug_instructions, raw_msg=True
                    )
                else:
                    raise YunohostError(str(exception), raw_msg=True)
            else:
                logger.error(exception)


class Configurations:

    type: str = ""

    def __init__(
        self,
        confs_properties: dict[str, Any],
        app: str,
        env: dict[str, Any],
        workdir: str | None = None,
    ):
        self.app = app
        self.workdir = workdir
        self.confs = {}
        self.confs["main"] = self.MainConfiguration(
            **confs_properties.pop("main", {}),
            env=env,
            id="main",
            type=self.type,
            app=app,
        )
        for key, values in confs_properties.items():
            if not isinstance(values, dict):
                raise YunohostError(
                    f"Uhoh, in {self.type} conf properties, {key} should be associated with a dict ... (did you meant <conf_id>.{key} ?)",
                    raw_msg=True,
                )
            self.confs[key] = self.ExtraConfiguration(
                **values, env=env, id=key, type=self.type, app=app
            )

        for conf_id, props in self.confs.items():
            for key, value in dict(props).items():
                # FIXME: in fact we probably want to interpret the if clause here, and ignore/continue in the appropriate case?
                if key == "if":
                    key = "if_clause"
                if isinstance(value, str):
                    if (
                        key.endswith("template")
                        and not value.startswith("/")
                        and workdir
                    ):
                        value = workdir.rstrip("/") + "/conf/" + value
                    setattr(
                        props,
                        key,
                        _hydrate_app_template(
                            value,
                            {"app": app, "conf_id": conf_id, **env},
                            raise_exception_if_missing_var=True,
                        ),
                    )

    def reload():
        raise NotImplementedError()


class NginxConfigurations(Configurations):

    type = "nginx"

    class NginxConfiguration(BaseConfiguration):

        @property
        def d_dir(self):
            return os.path.dirname(self.path) + f"/{self.app}.d"

        def d_dir_exists(self):
            return os.path.isdir(self.d_dir)

        def apply(
            self,
            dry_run: bool = False,
            force: bool = False,
        ):

            super().apply(dry_run=dry_run, force=force)

            if not dry_run:
                current_path = self.current_path
                if current_path and current_path != self.path:
                    current_d_dir = os.path.dirname(current_path) + f"/{self.app}.d"
                    if (
                        self.id == "main"
                        and os.path.isdir(current_d_dir)
                        and not self.d_dir_exists()
                    ):
                        os.rename(current_d_dir, self.d_dir)
                if self.id == "main" and not self.d_dir_exists():
                    os.makedirs(self.d_dir)

        def remove(self, dry_run: bool = False):

            super().remove(dry_run=dry_run)

            if dry_run:
                if self.id == "main" and os.path.isdir(self.d_dir):
                    logger.debug(f"Would also remove {self.d_dir}")
                    return

            # FIXME : or should we somehow backup the content of the .d dir ?
            if self.id == "main" and self.d_dir_exists():
                logger.debug(f"Removing {self.d_dir}")
                rm(self.d_dir, recursive=True)

    class MainConfiguration(NginxConfiguration):
        template: str = "nginx.conf"
        path: str = "/etc/nginx/conf.d/__DOMAIN__.d/__APP__.conf"

    class ExtraConfiguration(NginxConfiguration):
        template: str = "nginx-__CONF_ID__.conf"
        path: str = "/etc/nginx/conf.d/__DOMAIN__.d/__APP__.d/__CONF_ID__.conf"

    def reload():
        service_reload_or_restart("nginx")


ConfigurationsClassesByType = {c.type: c for c in Configurations.__subclasses__()}
