import os
import base64
import hashlib
import tempfile
import subprocess
import datetime
from logging import getLogger
from typing import Any, Literal, Generator
from pydantic import BaseModel

from moulinette import m18n
from moulinette.utils.filesystem import (
    read_file,
    write_to_file,
    chmod,
    chown,
    rm,
    mkdir,
)
from yunohost.app import (
    _hydrate_app_template,
    _get_app_settings,
    _set_app_settings,
    APPS_SETTING_PATH,
)
from yunohost.service import service_reload_or_restart
from yunohost.utils.error import YunohostError

logger = getLogger("yunohost.utils.resources")

DIR_TO_BACKUP_CONF_MANUALLY_MODIFIED = "/var/cache/yunohost/appconfbackup"

JSExpression = str
IFClause = Literal[True] | JSExpression


def sym_to_octal(sym: str) -> int:

    assert len(sym) == 9

    owner_perm, group_perm, other_perm = sym[:3], sym[3:6], sym[6:]

    owner_perm_octal = (
        (4 if "r" in owner_perm else 0)
        + (2 if "w" in owner_perm else 0)
        + (1 if "x" in owner_perm else 0)
    )

    group_perm_octal = (
        (4 if "r" in group_perm else 0)
        + (2 if "w" in group_perm else 0)
        + (1 if "x" in group_perm else 0)
    )

    other_perm_octal = (
        (4 if "r" in other_perm else 0)
        + (2 if "w" in other_perm else 0)
        + (1 if "x" in other_perm else 0)
    )

    return (
        0o100 * owner_perm_octal + 0o010 * group_perm_octal + 0o001 * other_perm_octal
    )


class BaseConfiguration(BaseModel):

    # if_clause: IFClause = True
    template: str
    path: str

    # FIXME: These should be settable via the manifest ... except for type = "app" for owner/group/perms ?
    id: str
    app: str
    type: str
    content: str | None = None
    env: dict[str, Any]
    owner: str = "root"
    group: str = "root"
    perms: str = "rw-r--r--"

    @property
    def name(self):
        return self.type if self.id != "main" else f"{self.type}.{self.id}"

    def exists(self):
        return os.path.exists(self.path)

    def render(self, template_content) -> None:
        self.content = _hydrate_app_template(
            template_content, self.env, raise_exception_if_missing_var=True
        )

    def checksum(self) -> str:
        assert self.content
        return hashlib.md5(self.content.encode()).hexdigest()

    def write(self, content):
        write_to_file(self.path, content)
        chown(self.path, self.owner, self.group)
        chmod(self.path, sym_to_octal(self.perms))

    def hydrate_properties(self, template_dir: str | None):

        for key, value in dict(self).items():
            if isinstance(value, str):
                if (
                    key.endswith("template")
                    and not value.startswith("/")
                    and template_dir
                ):
                    value = f"{template_dir}/{value}"
                setattr(
                    self,
                    key,
                    _hydrate_app_template(
                        value,
                        {"app": self.app, "conf_id": self.id, **self.env},
                        raise_exception_if_missing_var=True,
                    ),
                )

    ###############################################################
    # The 'original' conf refers to the original configuration    #
    # as generated by YunoHost / the app templates, *before* the  #
    # admins may have possibly manually edited it, compared to    #
    # the 'current' on-disk conf.                                 #
    ###############################################################

    def original_checksum(self):
        settings = _get_app_settings(self.app)
        checksum = (
            settings.get("_configurations", {})
            .get(f"{self.type}.{self.id}", {})
            .get("md5")
        )
        if not checksum:
            # Legacy way of storing checksums...
            legacy_checksum_setting_name = (
                f"checksum_{self.path.replace('/', '_').replace(' ', '_')}"
            )
            checksum = settings.get(legacy_checksum_setting_name)

        return checksum

    def original_content(self) -> str | None:

        original_checksum_ = self.original_checksum()
        if not original_checksum_:
            return None

        original_conf_file = os.path.join(
            APPS_SETTING_PATH, self.app, ".original_confs", original_checksum_
        )
        if os.path.exists(original_conf_file):
            try:
                # FIXME : should we revalidate the checksum here?
                return base64.b64decode(read_file(original_conf_file).encode()).decode()
            except Exception as e:
                logger.warning(f"Failed to read original conf for {self.name}? {e}")

        return None

    def save_new_original_content_and_checksum(self) -> None:

        assert self.content is not None

        new_checksum = self.checksum()
        original_conf_dir = os.path.join(APPS_SETTING_PATH, self.app, ".original_confs")
        original_conf_file = os.path.join(original_conf_dir, new_checksum)
        os.makedirs(original_conf_dir, exist_ok=True)
        chmod(original_conf_dir, 0o770)
        try:
            write_to_file(
                original_conf_file, base64.b64encode(self.content.encode()).decode()
            )
        except Exception as e:
            raise YunohostError(f"Failed to write original conf for {self.name}? {e}")

        app_settings = _get_app_settings(self.app)
        if "_configurations" not in app_settings:
            app_settings["_configurations"] = {}
        app_settings["_configurations"][f"{self.type}.{self.id}"] = {
            "path": self.path,
            "md5": new_checksum,
        }
        _set_app_settings(self.app, app_settings)

    ##########################################################
    # The 'current' conf refers to the current, on-disk file #
    ##########################################################

    @property
    def current_path(self) -> str | None:
        settings = _get_app_settings(self.app)
        path = (
            settings.get("_configurations", {})
            .get(f"{self.type}.{self.id}", {})
            .get("path")
        )
        if path:
            return path if os.path.exists(path) else None
        else:
            # Mostly to handle migration from packaging v2 ... is it enough though
            return self.path if os.path.exists(self.path) else None

    def current_content(self) -> str:
        current_path = self.current_path
        return read_file(current_path) if current_path else ""

    def current_checksum(self) -> str | None:
        current_content = self.current_content()
        return (
            hashlib.md5(current_content.encode()).hexdigest()
            if current_content
            else None
        )

    def backup_current_conf(self):

        current_path = self.current_path
        if not current_path:
            logger.warning(
                f"Configuration {self.path} doesn't exists and therefore won't be backedup?"
            )
            return

        timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_file = f"{DIR_TO_BACKUP_CONF_MANUALLY_MODIFIED}/{self.app}/{self.path}.backup.{timestamp}"
        mkdir(os.path.dirname(backup_file), mode=0o700, parents=True, uid="root")
        write_to_file(backup_file, self.current_content())

        # FIXME : i18n
        logger.warning(
            f"Configuration {current_path} was manually modified since the installation or last upgrade. It has been backedup in {backup_file}"
        )

    ##########################################################

    def was_manually_modified(self) -> bool:
        return self.current_checksum() != self.original_checksum()

    def attempt_merge(self) -> tuple[bool, str]:
        new_c = self.content
        original_c = self.original_content()
        current_c = self.current_content()
        assert new_c is not None
        assert original_c is not None
        assert current_c is not None

        with tempfile.NamedTemporaryFile(
            mode="w"
        ) as new_f, tempfile.NamedTemporaryFile(
            mode="w"
        ) as original_f, tempfile.NamedTemporaryFile(
            mode="w"
        ) as current_f:
            new_f.write(new_c)
            new_f.flush()
            original_f.write(original_c)
            original_f.flush()
            current_f.write(current_c)
            current_f.flush()
            p = subprocess.run(
                [
                    "git",
                    "merge-file",
                    "-p",
                    "--zdiff3",
                    "-L",
                    "current_config",
                    "-L",
                    "original_config",
                    "-L",
                    "new_config",
                    current_f.name,
                    original_f.name,
                    new_f.name,
                ],
                capture_output=True,
            )
            merged_content = p.stdout.decode()

        return (p.returncode == 0, merged_content)

    def original_vs_current_diff(self) -> str:
        original_c = self.original_content()
        current_c = self.current_content()
        assert original_c is not None
        assert current_c is not None

        with tempfile.NamedTemporaryFile(
            mode="w"
        ) as original_f, tempfile.NamedTemporaryFile(mode="w") as current_f:
            original_f.write(original_c)
            original_f.flush()
            current_f.write(current_c)
            current_f.flush()
            p = subprocess.run(
                [
                    "git",
                    "--no-pager",
                    "diff",
                    "--color",
                    "--no-index",
                    original_f.name,
                    current_f.name,
                ],
                capture_output=True,
            )

            out = p.stdout.decode().strip().split("\n")
            # [5:] is to Remove the diff header
            out = out[5:]
            # Remove the 'No newline at end of file' stuff...
            out = [l for l in out if not l.startswith("\\")]

            return "\n".join(out)

    def apply(
        self,
        dry_run: bool = False,
        force: bool = False,
    ):

        self.render(read_file(self.template))

        current_path = self.current_path
        if current_path is None:
            logger.debug(f"Adding {self.name} configuration ({self.path})")

        elif (
            not force
            and self.original_checksum() == self.checksum()
            and (not current_path or current_path == self.path)
        ):
            logger.debug(f"{self.name} does not need to be updated")
            return
        else:
            logger.debug(f"Updating {self.name} configuration ({self.path})")

        content_to_write = self.content
        conf_was_manually_modified = (
            self.was_manually_modified() if current_path is not None else False
        )

        if current_path and conf_was_manually_modified:
            merge_success, merged_content = self.attempt_merge()

            if merge_success:
                # FIXME: i18n
                logger.info(
                    f"Configuration {current_path} appears to have been manually modified. YunoHost was able to automatically merged your changes with the new configuration."
                )
                content_to_write = merged_content
            else:
                original_vs_current_diff = self.original_vs_current_diff()
                # FIXME: i18n
                logger.warning(
                    f"Configuration {current_path} appears to have been manually modified. YunoHost was unable to automatically merge your changes with the new configuration. It will therefore instead backup the current configuration and apply the new configuration. You may want to manually re-apply your changes:\n{'#'*16}\n{original_vs_current_diff}\n{'#'*16}"
                )

        if not dry_run:
            if current_path and conf_was_manually_modified:
                self.backup_current_conf()

            if current_path and current_path != self.path:
                logger.debug(
                    f"Removing old conf {current_path} since new conf is now at {self.path}"
                )
                rm(current_path)
            self.save_new_original_content_and_checksum()
            self.write(content_to_write)

    @classmethod
    def remove(klass, id, path, dry_run: bool = False):

        type_ = klass.__fields__["type"].default
        name = f"{type_}.{id}"

        if not os.path.exists(path):
            logger.warning(f"Configuration {name}: {path} is already absent")
            return

        if dry_run:
            logger.debug(f"Would remove {name} configuration ({path})")
            return

        if not dry_run:
            logger.debug(f"Removing {name} configuration ({path})")
            rm(path)


class AppConfigurationsManager:

    def __init__(self, app: str, wanted: dict, env: dict[str, str], workdir=None) -> None:
        self.app = app
        self.wanted = wanted
        self.workdir = workdir
        self.env = env

        if "configurations" not in self.wanted:
            self.wanted["configurations"] = {}

    def compute_todos(
        self,
    ) -> Generator[
        tuple[
            Literal["add", "update", "remove"],
            str,
            str,
            BaseConfiguration | None,
            str | None,
        ],
        None,
        None,
    ]:

        conf_settings = _get_app_settings(self.app).get("_configurations", {})
        current_confs: dict[tuple, str] = {
            tuple(k.split(".")): v["path"] for k, v in conf_settings.items()
        }
        wanted_confs: dict[tuple, BaseConfiguration] = {
            (c.type, c.id): c for c in self.load_wanted_confs()
        }

        for key, path in current_confs.items():
            type_, id_ = key
            if key not in wanted_confs:
                yield ("remove", type_, id_, None, path)

        for key, conf in wanted_confs.items():
            type_, id_ = key
            if key not in current_confs:
                yield ("add", type_, id_, conf, None)
            else:
                yield ("update", type_, id_, conf, None)

    def apply(
        self,
        rollback_and_raise_exception_if_failure,
        operation_logger=None,
        dry_run=False,
    ) -> None:
        todos = list(self.compute_todos())
        completed = []
        # rollback = False
        exception = None

        for todo, type_, id_, new, path_to_remove in todos:
            name = type_ if id_ == "main" else f"{type_}.{id_}"
            try:
                if todo == "remove":
                    assert path_to_remove
                    logger.info(f"Removing {name} configuration...")
                    ConfigurationClassesByType[type_].remove(
                        id_, path_to_remove, dry_run=dry_run
                    )
                elif todo == "add":
                    assert new
                    logger.info(f"Adding {name} configuration...")
                    new.apply(dry_run=dry_run)
                elif todo == "update":
                    assert new
                    logger.info(f"Updating {name} configuration...")
                    new.apply(dry_run=dry_run)
                if not dry_run:
                    ConfigurationClassesByType[type_].reload()
            except (KeyboardInterrupt, Exception) as e:
                exception = e
                if isinstance(e, KeyboardInterrupt):
                    logger.error(m18n.n("operation_interrupted"))
                else:
                    logger.error(f"Failed to {todo} {name} configuration : {e}")
                if rollback_and_raise_exception_if_failure:
                    # rollback = True
                    completed.append((todo, type_, id_, new, path_to_remove))
                    break
                else:
                    pass
            else:
                completed.append((todo, type_, id_, new, path_to_remove))

        # FIXME : hmmmm do we really want to rollback, is it doable, etc ...

        # if rollback:
        #     for todo, type_, id_, new, path_to_remove in completed:
        #         name = type_ if id_ == "main" else f"{type_}.{id_}"
        #         try:
        #             # (NB. here we want to undo the todo)
        #             if todo == "remove":
        #                 assert old
        #                 # FIXME : i18n, better info strings
        #                 logger.info(f"Rollingback {name} configuration...")
        #                 old.apply(dry_run=dry_run)
        #             elif todo == "add":
        #                 assert new
        #                 logger.info(f"Removing {name} configuration...")
        #                 new.remove(dry_run=dry_run)
        #             elif todo == "update":
        #                 assert old
        #                 logger.info(f"Rollingback {name} configuration...")
        #                 old.apply(dry_run=dry_run)
        #             if not dry_run:
        #                 ConfigurationsClassesByType[type_].reload()
        #         except (KeyboardInterrupt, Exception) as e:
        #             if isinstance(e, KeyboardInterrupt):
        #                 logger.error(m18n.n("operation_interrupted"))
        #             else:
        #                 logger.error(f"Failed to rollback {name} : {e}")

        if exception:
            if rollback_and_raise_exception_if_failure:
                logger.error(
                    m18n.n("app_regenconf_failed", app=self.app, error=exception)
                )
                if operation_logger:
                    failure_message_with_debug_instructions = operation_logger.error(
                        str(exception)
                    )
                    raise YunohostError(
                        failure_message_with_debug_instructions, raw_msg=True
                    )
                else:
                    raise YunohostError(str(exception), raw_msg=True)
            else:
                logger.error(exception)

    def load_wanted_confs(self) -> list[BaseConfiguration]:

        confs = []

        for type_, confs_properties in self.wanted["configurations"].items():

            confs_properties = confs_properties.copy()
            if type_ not in ConfigurationClassesByType:
                raise YunohostError(f"Unknown configuration type {type_}")
            main_properties = confs_properties.pop("main", {})
            confs.append(
                ConfigurationClassesByType[type_](
                    **main_properties,
                    id="main",
                    env=self.env,
                    type=type_,
                    app=self.app,
                )
            )
            for key, values in confs_properties.items():

                if not isinstance(values, dict):
                    raise YunohostError(
                        f"Uhoh, in {type_} conf properties, {key} should be associated with a dict ... (did you meant <conf_id>.{key} ?)",
                        raw_msg=True,
                    )

                # FIXME : Handle IF clause here ?!

                confs.append(
                    ConfigurationClassesByType[type_](
                        **values,
                        id=key,
                        env=self.env,
                        type=type_,
                        app=self.app,
                    )
                )

        template_dir = (self.workdir.rstrip("/") + "/conf/") if self.workdir else None
        for conf in confs:
            conf.hydrate_properties(template_dir=template_dir)

        return confs


class NginxConfiguration(BaseConfiguration):

    type = "nginx"

    def __init__(self, *args, **kwargs):

        # Default values for main and extras
        if kwargs["id"] == "main":
            self.template = "nginx.conf"
            self.path = "/etc/nginx/conf.d/__DOMAIN__.d/__APP__.conf"
        else:
            self.template = "nginx-__CONF_ID__.conf"
            self.path = "/etc/nginx/conf.d/__DOMAIN__.d/__APP__.d/__CONF_ID__.conf"

        super().__init__(*args, **kwargs)

    @property
    def d_dir(self):
        return os.path.dirname(self.path) + f"/{self.app}.d"

    def d_dir_exists(self):
        return os.path.isdir(self.d_dir)

    def apply(
        self,
        dry_run: bool = False,
        force: bool = False,
    ):

        super().apply(dry_run=dry_run, force=force)

        if not dry_run:
            current_path = self.current_path
            if current_path and current_path != self.path:
                current_d_dir = os.path.dirname(current_path) + f"/{self.app}.d"
                if (
                    self.id == "main"
                    and os.path.isdir(current_d_dir)
                    and not self.d_dir_exists()
                ):
                    os.rename(current_d_dir, self.d_dir)
            if self.id == "main" and not self.d_dir_exists():
                os.makedirs(self.d_dir)

    @classmethod
    def remove(klass, id, path, dry_run: bool = False):

        super().remove(id, path, dry_run=dry_run)

        # FIXME
        d_dir = NotImplementedError()

        if dry_run:
            if id == "main" and os.path.isdir(d_dir):
                logger.debug(f"Would also remove {d_dir}")
                return

        # FIXME : or should we somehow backup the content of the .d dir ?
        if id == "main" and os.path.isdir(d_dir):
            logger.debug(f"Removing {d_dir}")
            rm(d_dir, recursive=True)

    @staticmethod
    def reload():
        service_reload_or_restart("nginx")


ConfigurationClassesByType = {
    c.__fields__["type"].default: c for c in BaseConfiguration.__subclasses__()
}
