#!/bin/bash

set -eu

. /usr/share/yunohost/helpers.d/filesystem

backup_dir="${1}/conf/ldap"

# Back up the configuration
ynh_backup "/etc/ldap/slapd.conf" "${backup_dir}/slapd.conf"
sudo slapcat -b cn=config -l "${backup_dir}/cn=config.master.ldif"

# Back up the database
sudo slapcat -b dc=yunohost,dc=org -l "${backup_dir}/dc=yunohost-dc=org.ldif"
