#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

# Backup destination
backup_dir="${1}/conf/ssh"

# Backup the configuration
if [ -d /etc/ssh/ ]; then
    ynh_backup "/etc/ssh" "$backup_dir"
else
    echo "SSH is not installed"
fi
