#!/bin/bash

set -eu

. /usr/share/yunohost/helpers.d/filesystem

backup_dir="${1}/conf/ssh"

if [ -d /etc/ssh/ ]; then
    ynh_backup "/etc/ssh" "$backup_dir"
else
    echo "SSH is not installed"
fi
