#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

# Backup destination
backup_dir="${1}/conf/ssowat"

# Backup the configuration
ynh_backup "/etc/ssowat" "$backup_dir"
