#!/bin/bash

set -eu

. /usr/share/yunohost/helpers.d/filesystem

for f in $(find /home/* -type d -prune | awk -F/ '{print $NF}'); do
    if [[ ! "$f" =~ ^yunohost|lost\+found ]]; then
        ynh_backup "/home/$f" "${1}/data/home/$f" 1
    fi
done
