#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
. /usr/share/yunohost/helpers.d/filesystem

# Backup destination
backup_dir="${1}/conf/ynh/certs"

# Backup certificates
ynh_backup "/etc/yunohost/certs" "$backup_dir"
