#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

# Backup destination
backup_dir="${1}/conf/ynh/certs"

# Backup certificates
ynh_backup "/etc/yunohost/certs" "$backup_dir"
