#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

# Backup destination
backup_dir="${1}/etc/dkim"

# Backup the configuration
ynh_backup "/etc/dkim" "$backup_dir"
