#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
. /usr/share/yunohost/helpers.d/filesystem

# Backup destination
backup_dir="${1}/data/mail"

# Backup mails
ynh_backup /var/mail "$backup_dir" 1
