#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
. /usr/share/yunohost/helpers.d/filesystem

# Backup destination
backup_dir="${1}/conf/xmpp"

# Backup the configuration
ynh_backup /etc/metronome "${backup_dir}/etc"
ynh_backup /var/lib/metronome "${backup_dir}/var"
