#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
. /usr/share/yunohost/helpers.d/filesystem

# Backup destination
backup_dir="${1}/conf/nginx"

# Backup the configuration
ynh_backup "/etc/nginx/conf.d" "$backup_dir"
