#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

# Backup destination
backup_dir="${1}/conf/nginx"

# Backup the configuration
ynh_backup "/etc/nginx/conf.d" "$backup_dir"
