#!/bin/bash

# Exit hook on subcommand error or unset variable
set -eu

# Source YNH helpers
. /usr/share/yunohost/helpers.d/filesystem

# Backup destination
backup_dir="${1}/conf/cron"

# Backup the configuration
for f in $(ls -1B /etc/cron.d/yunohost*); do
  ynh_backup "$f" "${backup_dir}/${f##*/}"
done
