#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Execute a command with Composer
#
# Will use `$install_dir` as workdir unless `$composer_workdir` exists (but that shouldnt be necessary)
#
# You may also define `composer_user=root` prior to call this helper if you
# absolutely need composer to run as root, but this is discouraged...
#
# usage: ynh_composer_exec commands
ynh_composer_exec() {
    local workdir="${composer_workdir:-$install_dir}"

    if [[ "$(whoami)" == "root" ]]
    then
        COMPOSER_HOME="$workdir/.composer" \
        COMPOSER_MEMORY_LIMIT=-1 \
        sudo -E -u "${composer_user:-$app}" \
        "php$php_version" "$workdir/composer.phar" "$@" \
        -d "$workdir" --no-interaction --no-ansi 2>&1
    else
        COMPOSER_HOME="$workdir/.composer" \
        COMPOSER_MEMORY_LIMIT=-1 \
        "php$php_version" "$workdir/composer.phar" "$@" \
        -d "$workdir" --no-interaction --no-ansi 2>&1
    fi
    
}
