#!/usr/bin/env bash
#
# Copyright (c) 2024 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

readonly RBENV_ROOT="/opt/rbenv"
export RBENV_ROOT

_ynh_load_ruby_in_path_and_other_tweaks() {

    # Get the absolute path of this version of Ruby
    ruby_dir="$RBENV_ROOT/versions/$app/bin"

    # Load the path of this version of ruby in $PATH
    if [[ :$PATH: != *":$ruby_dir"* ]]; then
        PATH="$ruby_dir:$PATH"
    fi

    # Export PATH such that it's available through sudo -E / ynh_exec_as $app
    export PATH

    # This is in full lowercase such that it gets replaced in templates
    path_with_ruby="$PATH"
    PATH_with_ruby="$PATH"

    # Sets the local application-specific Ruby version
    pushd "${install_dir}"
        "$RBENV_ROOT/bin/rbenv" local "$ruby_version"
    popd
}

# Auto-load Ruby path tweaks if this app uses the ruby resource in the manifest
if [ -n "${ruby_version:-}" ] && (cat "$YNH_APP_BASEDIR/manifest.toml" | toml_to_json | jq -e ".resources.ruby" > /dev/null); then
    _ynh_load_ruby_in_path_and_other_tweaks
fi
